sudo: false
language: python
python:
  - "3.5"
addons:
-  apt:
-    packages:
      - ffmpeg
      - libblas-dev
      - liblapack-dev
      - gfortran 
      
install: 
  - pip install -r requirements_conda.txt
  #- conda install -q --file=requirements_conda.txt
  - pip install -r requirements.txt
  - pip install -r requirements2.txt
  - pip install -r requirements_scikit.txt
  - pip install -r requirements_ext.txt
script:
    - python setup.py unittests
