language: python
python:
  - "3.4"
install:
  - sudo apt-get update
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION actuariat_test
  #- conda install -r requirements.txt
  - conda install numpy
  - conda install scipy
  - conda install scikit-learn
  - conda install matplotlib
  - conda install ipython  
  - conda install numpy
  #- source activate test-environment
  - python setup.py install -r requirements_ext.txt
script:
  - python setup.py unittests
